### ISSUE TITLE
[BUG] /cq view returns an NPE if there's an active competitive event

### ISSUE THREAD

**Issue by Faun471** [wsaada19/CommunityQuests#5]
Error Message: https://paste.gg/p/anonymous/674b908be0724fd3b949c74063289bc7

To reproduce:
1. Start a competitive event
2. Run the command `/cq view`

An error message will be sent to the console.

**Comment by wsaada19** [comment]
Issue should be solved in 1.01, the latest release is on spigot. Code changes will be merged into master shortly.
